# Generated by Django 6.0.1 on 2026-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='media/avatars')),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
