# Generated by Django 4.2.7 on 2026-01-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
