# Generated by Django 4.2.7 on 2026-01-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_user_comment_author_remove_comment_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
    ]
