# Generated by Django 6.0.1 on 2026-01-28 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
        ('posts', '0005_remove_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(default='like', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('post', 'user', 'type')},
        ),
    ]
